### ISSUE TITLE
Add quarterly checkpoint baselines

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule.Rules.Azure#399]
As new rules continue to be added not all rules may be able to be accepted on a monthly basis, potentially breaking a CI pipeline.

While an earlier module version could be used, this may not include rule bug fixes.

Instead a quarterly baseline would allow check pointing of rules and rule bug fixes to be integrated without all rules being accepted in an immediate breaking issues affecting a sprint.

For example:

```yaml
---
# Synopsis: Baseline for GA rules released June 2020 or prior
kind: Baseline
metadata:
  name: Azure.GA_2020_06
spec:
  binding:
    targetName:
    - ResourceName
    - FullName
    - name
    targetType:
    - ResourceType
    - type
    - Extension
    field:
      resourceId: [ 'ResourceId' ]
      subscriptionId: [ 'SubscriptionId' ]
      resourceGroupName: [ 'ResourceGroupName' ]
  rule:
    tag:
      release: GA
      group:
      - '2020_06'

```

This would require all rules to be tagged with a group marking to allow tracking.
